---
- name: Setup Prometheus node exporter
  include: prometheus.yml
  tags:
    - prometheus

- name: Setup SNMP
  include: snmp.yml
  tags:
    - snmp

- name: Forward rsyslog messages
  include: rsyslog.yml
  tags:
    - rsyslog

- name: Run nclu show command every minute
  include: nclu.yml
  tags:
    - nclu
...
