---
- name: Forward rsyslog messages to remote rsyslog server using lineinfile
  lineinfile:
    path: /etc/rsyslog.d/11-remotesyslog.conf
    create: true
    line: "*.*   @{{ cl_oob_server }}:{{ rsyslog_port }}   # UDP"

- name: Add rsyslog to vrf config using lineinfile
  lineinfile:
    path: /etc/vrf/systemd.conf
    create: true
    line: "rsyslog"

- name: stop service rsyslog, if running
  systemd:
    name: rsyslog
    state: stopped

- name: disable service rsyslog
  systemd:
    name: rsyslog
    enabled: no

- name: force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: start service rsyslog@mgmt
  systemd:
    name: rsyslog@mgmt
    state: started

- name: enable service rsyslog@mgmt
  systemd:
    name: rsyslog@mgmt
    enabled: yes
...
