---
- name: Forward rsyslog messages to remote rsyslog server using lineinfile
  lineinfile:
    path: /etc/rsyslog.d/11-remotesyslog.conf
    create: true
    line: "*.*   @{{ rsyslog_server }}:{{ rsyslog_port }}   # UDP"
  notify: restart rsyslog

- name: stop rsyslog
  service:
    name: rsyslog
    state: stopped

- name: disable rsyslog
  service:
    name: rsyslog
    enabled: no
  notify: restart rsyslog

- name: start rsyslog@mgmt
  service:
    name: rsyslog@mgmt
    state: started
  notify: restart rsyslog
      
- name: enable rsyslog@mgmt
  service:
    name: rsyslog@mgmt
    enabled: yes
  notify: restart rsyslog
...
