---
- name: Forward rsyslog messages to remote rsyslog server using lineinfile
  lineinfile:
    path: /etc/rsyslog.d/11-remotesyslog.conf
    create: true
    line: "*.*   @{{ cl_oob_server }}:{{ rsyslog_port }}   # UDP"

- name: Add rsyslog to vrf config using lineinfile
  lineinfile:
    path: /etc/vrf/systemd.conf
    create: true
    line: "rsyslog"

- name: stop rsyslog
  service:
    name: rsyslog
    state: stopped

- name: disable rsyslog
  service:
    name: rsyslog
    enabled: no

- name: enable rsyslog@mgmt
  service:
    name: rsyslog@mgmt
    enabled: yes

- name: start rsyslog@mgmt
  service:
    name: rsyslog@mgmt
    state: started
...
