---
- name: create and modify snmpd.conf
  template:
    src: snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
    mode: 0644
  notify: restart snmpd

- name: enable snmpd at boottime
  service:
    name: snmpd
    enabled: yes
...
