---
- name: Restart node_exporter
  systemd:
    name: node_exporter@mgmt
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Restart snmpd
  service:
    name: snmpd
    state: restarted
